server:
  port: 8089
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/v3/api-docs,/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth(?<segment>.*), $\{segment}
        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/v3/api-docs,/users/v3/api-docs/**
          filters:
            - RewritePath=/users(?<segment>.*), $\{segment}
        - id: payment-service-docs
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/v3/api-docs,/payments/v3/api-docs/**
          filters:
            - RewritePath=/payments(?<segment>.*), $\{segment}
        - id: operator-service-docs
          uri: lb://OPERATOR-SERVICE
          predicates:
            - Path=/operators/v3/api-docs,/operators/v3/api-docs/**
          filters:
            - RewritePath=/operators(?<segment>.*), $\{segment}
        - id: recharge-service-docs
          uri: lb://RECHARGE-SERVICE
          predicates:
            - Path=/recharges/v3/api-docs,/recharges/v3/api-docs/**
          filters:
            - RewritePath=/recharges(?<segment>.*), $\{segment}
        - id: notification-service-docs
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/v3/api-docs,/notifications/v3/api-docs/**
          filters:
            - RewritePath=/notifications(?<segment>.*), $\{segment}
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>.*), $\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>.*), $\{segment}
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments(?<segment>.*), $\{segment}
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications(?<segment>.*), $\{segment}
        - id: recharge-service
          uri: lb://RECHARGE-SERVICE
          predicates:
            - Path=/recharges/**
          filters:
            - RewritePath=/recharges(?<segment>.*), $\{segment}
        - id: operator-service
          uri: lb://OPERATOR-SERVICE
          predicates:
            - Path=/operators/**
          filters:
            - RewritePath=/operators(?<segment>.*), $\{segment}
  devtools:
    restart:
      enabled: false

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    urls-primary-name: auth-service
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: user-service
        url: /users/v3/api-docs
      - name: operator-service
        url: /operators/v3/api-docs
      - name: payment-service
        url: /payments/v3/api-docs
      - name: recharge-service
        url: /recharges/v3/api-docs
      - name: notification-service
        url: /notifications/v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:secretarjituttt123455667ksfbbfXY}

logging:
  file:
    name: logs/Api-Gateway.log
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
