server:
  port: 8081
  forward-headers-strategy: framework

spring:
  cloud:
    config:
      enabled: true
      import-check:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/OMNI_Recharge
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    servers:
      - url: http://localhost:8089
        description: API Gateway
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:secretarjituttt123455667ksfbbfXY}

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/OMNI_Recharge

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
